hackernews:
  name: Hacker News
  category: Tech
theblaze:
  name: The Blaze
  category: Conservative News
nypost:
  name: New York Post
  category: Conservative News
huffpost_blogs:
  name: Huffington Post Blogs
  category: Liberal News
thinkprogress:
  name: ThinkProgress
  category: Liberal News
tmz:
  name: TMZ
  category: Entertainment
  default: true
giantbomb:
  name: Giant Bomb
  category: Games
kotaku:
  name: Kotaku
  category: Games
buzzfeed:
  name: BuzzFeed
  category: Trash
  default: true
upworthy:
  name: Upworthy
  category: Trash
  default: true
gawker:
  name: Gawker
  category: Trash
  default: false
jezebel:
  name: Jezebel
  category: Entertainment
  default: false
io9:
  name: io9
  category: Entertainment
  default: false
tested:
  name: Tested
  category: Tech
r_politics:
  name: r/politics
  category: Reddit
r_funny:
  name: r/funny
  category: Reddit