hackernews:
  name: Hacker News
  category: Tech
theblaze:
  name: The Blaze
  category: Opinion
  default: true
nypost:
  name: New York Post
  category: Opinion
  default: true
huffpost_blogs:
  name: Huffington Post Blogs
  category: Opinion
  default: true
thinkprogress:
  name: ThinkProgress
  category: Opinion
  default: true
tmz:
  name: TMZ
  category: Entertainment
  default: true
giantbomb:
  name: Giant Bomb
  category: Games
  default: true
kotaku:
  name: Kotaku
  category: Games
  default: true
buzzfeed:
  name: BuzzFeed
  category: Trash
  default: true
upworthy:
  name: Upworthy
  category: Trash
  default: true
gawker:
  name: Gawker
  category: Trash
  default: true
defamer:
  name: Defamer
  category: Entertainment
  default: true
jezebel:
  name: Jezebel
  category: Entertainment
  default: true
io9:
  name: io9
  category: Entertainment
  default: true
tested:
  name: Tested
  category: Tech
  default: true
r_politics:
  name: r/politics
  category: Reddit
r_funny:
  name: r/funny
  category: Reddit